" Encoding
set termencoding=utf-8
set t_Co=256

" Don't be combatible with vi
set nocompatible

" Backspace
set backspace=indent,eol,start

" Turn on syntax highlighting
syntax on

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'vim-airline/vim-airline'
Plugin 'tomtom/tcomment_vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'tomasr/molokai'

call vundle#end()

" Set colorscheme
colorscheme molokai

" Search options
set incsearch
set hlsearch
set ignorecase
set infercase
"Scrolling
set scrolloff=3
set sidescrolloff=2

"Highlight matching parens
set showmatch

" Create backups
set backup

" Show current command
set showcmd

" Display statusline
set laststatus=2

" Use relative numbers (hybrid)
set relativenumber
set number

" Indent of 4 spaces
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" indent
set autoindent
filetype plugin on
filetype indent on

" Show whitespace
set list listchars=tab:>-,trail:.,extends:>,nbsp:_

" Disable bells
set noerrorbells

" Mappings

" Toggle line numbers
nmap <C-N><C-N> :set invrelativenumber<CR>:set invnumber<CR>

" Disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>


set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_loc_list_height=11
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_c_no_default_include_dirs = 1
let g:syntastic_c_no_include_search = 1
let g:syntastic_c_remove_include_errors = 1
let g:syntastic_disabled_filetypes=['c']
let g:syntastic_c_checkers=['']


let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }
nnoremap <C-w>E :SyntasticCheck<CR> :SyntasticToggleMode<CR>
