" Encoding
set termencoding=utf-8
set t_Co=256

" Don't be combatible with vi
set nocompatible

" Backspace
set backspace=indent,eol,start

" Turn on syntax highlighting
syntax on

" Set hidden
set hidden

filetype off

" vim-plug install
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'tomtom/tcomment_vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tomasr/molokai'
Plug 'leafOfTree/vim-svelte-plugin'
Plug 'leafgarland/typescript-vim'
Plug 'tpope/vim-haml'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
call plug#end()

" Set colorscheme
colorscheme molokai

" Search options
set incsearch
set hlsearch
set ignorecase
set infercase
"Scrolling
set scrolloff=3
set sidescrolloff=2

"Highlight matching parens
set showmatch

" Create backups
set backup

" Show current command
set showcmd

" Display statusline
set laststatus=2

" Use relative numbers (hybrid)
set relativenumber
set number

" Indent of 4 spaces
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" indent
set autoindent
filetype plugin on
filetype indent on

" Show whitespace
set list listchars=tab:>-,trail:.,extends:>,nbsp:_

" Disable bells
set noerrorbells

" Mappings

" Toggle line numbers
nmap <C-N><C-N> :set invrelativenumber<CR>:set invnumber<CR>

" Disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>

" More natural split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Use jk to <esc>
inoremap jk <esc>
" Unmap esc to force using j k
inoremap <esc> <nop>

" More natural split opening
set splitbelow
set splitright

set statusline+=%#warningmsg#
set statusline+=%*

